object BuildDependenciesVersions {
    const val KOTLIN = "1.5.20"
    const val APPCOMPAT = "1.3.0"
    const val MATERIAL = "1.4.0-rc01"
    const val COROUTINES = "1.5.0"
    const val NAVIGATION = "2.3.5"
    const val LIFECYCLE = "2.3.1"
    const val LIFECYCLE_EXTENSION = "2.2.0"
    const val CORE_KTX = "1.5.0"
    const val FRAGMENT_KTX = "1.3.4"
    const val CONSTRAIN_LAYOUT = "2.0.4"
    const val DAGGER = "2.37"
    const val TIMBER = "4.7.1"
    const val PLAY_CORE = "1.10.0"
    const val LEAKCANARY = "2.7"

    // Tests
    const val TEST = "1.3.0"
    const val EXT = "1.1.2"
    const val ARCH_CORE = "2.1.0"
    const val JUNIT = "4.13.1"
    const val ROBOELECTRIC = "4.4"
    const val MOCKK = "1.10.2"
    const val ASSERTJ = "3.17.2"
    const val ESPRESSO = "3.3.0"
    const val FRAGMENT_TEST = "1.2.5"
    const val MOCK_WEB_SERVER = "4.9.0"
}